name: Weekly activity report

on:
  schedule:
    - cron: '0 12 * * 1'
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: create service-secrets.json
        run: |
          echo "$SERVICE_SECRETS" > service-secrets.json
        env:
          SERVICE_SECRETS: ${{ secrets.SERVICE_SECRETS }}
      - name: Install dependencies
        run: |
          uv sync

      - name: Generate weekly summary
        run: |
          uv run traceback-with-variables napari_dashboard.get_weekly_summary --send-zulip --channel ${{ (github.event_name == 'schedule') && 'developer-updates' || '"metrics and analytics"' }}
        env:
          PEPY_KEY: ${{ secrets.PEPY_KEY }}
          GH_TOKEN_: ${{ secrets.GITHUB_TOKEN }}
          ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }}
